# Generated by scripts/update-tap.sh in the chalk repository. Do not edit by hand.
class Chalk < Formula
  desc "Sandboxed, budget-capped Claude Code agent harness for GitHub and GitLab repos"
  homepage "https://github.com/khalaharvi/chalk"
  url "https://github.com/khalaharvi/chalk/archive/refs/tags/v0.5.0.tar.gz"
  sha256 "dc09d54c74399e102c1ac2f04d1a35df42dce1d6cfbb02cf0b9cbf545736a574"
  license "Apache-2.0"
  head "https://github.com/khalaharvi/chalk.git", branch: "main"

  depends_on "bash"
  depends_on "gh"
  depends_on "glab"
  depends_on "jq"

  def install
    libexec.install "bin", "lib", "share"
    # Run under Homebrew's bash, never whichever bash comes first on PATH.
    inreplace libexec/"bin/chalk", %r{\A#!/usr/bin/env bash$}, "#!#{Formula["bash"].opt_bin}/bash"
    (bin/"chalk").write_env_script libexec/"bin/chalk", CHALK_HOME: libexec
  end

  def caveats
    <<~EOS
      Chalk needs a running Docker runtime (Docker Desktop, OrbStack or Colima)
      and agent credentials in your environment, for example:
        export CLAUDE_CODE_OAUTH_TOKEN=...   # from: claude setup-token
      Then run:
        chalk doctor
    EOS
  end

  test do
    assert_equal "#!#{Formula["bash"].opt_bin}/bash", (libexec/"bin/chalk").readlines.first.chomp
    assert_equal version.to_s, shell_output("#{bin}/chalk version").strip
  end
end
