# Generated by scripts/release.sh in the chalk repository. Do not edit by hand.
class Chalk < Formula
  desc "Sandboxed, budget-capped Claude Code agent harness for GitLab repos"
  homepage "https://github.com/khalaharvi/chalk"
  url "https://github.com/khalaharvi/chalk/archive/refs/tags/v0.4.0.tar.gz"
  sha256 "a4e8a61af1d2a025c84b830ce5035575363e0b91092d8d9d642e57e697691899"
  license "Apache-2.0"
  head "https://github.com/khalaharvi/chalk.git", branch: "main"

  depends_on "glab"
  depends_on "jq"

  def install
    libexec.install "bin", "lib", "share"
    (bin/"chalk").write_env_script libexec/"bin/chalk", CHALK_HOME: libexec
  end

  def caveats
    <<~EOS
      Chalk needs a running Docker runtime (Docker Desktop, OrbStack or Colima)
      and agent credentials in your environment, for example:
        export CLAUDE_CODE_OAUTH_TOKEN=...   # from: claude setup-token
      Then run:
        chalk doctor
    EOS
  end

  test do
    assert_equal version.to_s, shell_output("#{bin}/chalk version").strip
  end
end
